name: bm25
description: A Dart implementation of the BM25 ranking algorithm for full-text search
version: 2.2.3
homepage: https://github.com/mirkancal/bm25

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
  collection: ^1.18.0
  async: ^2.11.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0
